### HW2:

In [1]:
import numpy as np
import pandas as pd

1. Define two custom numpy arrays, say A and B. Generate two new numpy arrays by stacking A and B vertically and horizontally.

In [4]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([6, 7, 8, 9, 10])

AB_vert = np.vstack((A,B))
AB_horiz = np.hstack((A,B))

print(f"A and B stacked vertically is: \n {AB_vert}")
print(f"A and B stacked horizontally is: \n {AB_horiz}")

A and B stacked vertically is: 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
A and B stacked horizontally is: 
 [ 1  2  3  4  5  6  7  8  9 10]


2. Find common elements between A and B. [Hint : Intersection of two sets]

In [7]:
A = np.array([1, 1, 3, 5, 7])
B = np.array([1, 4, 6, 7, 8])

C = np.intersect1d(A, B)

print(f"The array of common elements between A and B are {C}.")

The array of common elements between A and B are [1 7].


3. Extract all numbers from A which are within a specific range. eg between 5 and 10. [Hint: np.where() might be useful or boolean masks]


In [46]:
A = np.arange(20)
lower = 5; upper = 10

B = A[A > lower]
B = B[B < upper]
print(f"These are all the numbers within A that are in range ({lower},{upper}) : {B}")

These are all the numbers within A that are in range (5,10) : [6 7 8 9]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0
```
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
```

In [100]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

petal_length_filt = iris_2d[:,2][iris_2d[:,2] > 1.5]
iris_2d[:,2] = np.where(iris_2d[:,2] <= 1.5, iris_2d[:,2], np.nan)

sepal_length_filt = iris_2d[:,0][iris_2d[:,0] < 5.0]
iris_2d[:,0] = np.where(iris_2d[:,0] >= 5.0, iris_2d[:,0], np.nan)

print(f"The filtered petal lengths are: \n{petal_length_filt}")
print(f"The filtered sepal lengths are: \n{sepal_length_filt}")
print(f"The original table with filtered data removed is: \n{iris_2d}")

for el in iris_2d[:,2]:
    if el > 1.5 and el != np.nan:
        raise ValueError("Third column has misfiltered data with petal length <= 1.5")
for el in iris_2d[:,0]:
    if el < 5:
        raise ValueError("First column has misfiltered data with sepallength > 5.0")

The filtered petal lengths are: 
[1.7 1.6 1.7 1.7 1.7 1.9 1.6 1.6 1.6 1.6 1.6 1.9 1.6 4.7 4.5 4.9 4.  4.6
 4.5 4.7 3.3 4.6 3.9 3.5 4.2 4.  4.7 3.6 4.4 4.5 4.1 4.5 3.9 4.8 4.  4.9
 4.7 4.3 4.4 4.8 5.  4.5 3.5 3.8 3.7 3.9 5.1 4.5 4.5 4.7 4.4 4.1 4.  4.4
 4.6 4.  3.3 4.2 4.2 4.2 4.3 3.  4.1 6.  5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8
 6.1 5.1 5.3 5.5 5.  5.1 5.3 5.5 6.7 6.9 5.  5.7 4.9 6.7 4.9 5.7 6.  4.8
 4.9 5.6 5.8 6.1 6.4 5.6 5.1 5.6 6.1 5.6 5.5 4.8 5.4 5.6 5.1 5.1 5.9 5.7
 5.2 5.  5.2 5.4 5.1]
The filtered sepal lengths are: 
[4.9 4.7 4.6 4.6 4.4 4.9 4.8 4.8 4.3 4.6 4.8 4.7 4.8 4.9 4.9 4.4 4.5 4.4
 4.8 4.6 4.9 4.9]
The original table with filtered data removed is: 
[[5.1 3.5 1.4 0.2]
 [nan 3.  1.4 0.2]
 [nan 3.2 1.3 0.2]
 [nan 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 nan 0.4]
 [nan 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [nan 2.9 1.4 0.2]
 [nan 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [nan 3.4 nan 0.2]
 [nan 3.  1.4 0.1]
 [nan 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5

1. From df filter the 'Manufacturer', 'Model' and 'Type' for every 20th row starting from 1st (row 0).

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [116]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

df[::20].filter(items=['Manufacturer', 'Model', 'Type'])

Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small

2. Replace missing values in Min.Price and Max.Price columns with their respective mean.

```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```

In [225]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Replacing nan values with the mean of each column
min_price_series = df['Min.Price'][:].replace(np.nan, df['Min.Price'].mean()) 
max_price_series = df['Max.Price'][:].replace(np.nan, df['Max.Price'].mean())

# Forming a dataframe with the series
price_dict = {'Min.Price': min_price_series, 'Max.Price': max_price_series}
price_df = pd.DataFrame(data=price_dict)

# Overwriting original values with our substitutions
df[['Min.Price', 'Max.Price']] = price_df[['Min.Price', 'Max.Price']]

df

Manufacturer    Model     Type  Min.Price  Price  Max.Price  MPG.city  \
0         Acura  Integra    Small  12.900000   15.9  18.800000      25.0   
1           NaN   Legend  Midsize  29.200000   33.9  38.700000      18.0   
2          Audi       90  Compact  25.900000   29.1  32.300000      20.0   
3          Audi      100  Midsize  17.118605   37.7  44.600000      19.0   
4           BMW     535i  Midsize  17.118605   30.0  21.459091      22.0   
..          ...      ...      ...        ...    ...        ...       ...   
88   Volkswagen  Eurovan      Van  16.600000   19.7  22.700000      17.0   
89   Volkswagen   Passat  Compact  17.600000   20.0  22.400000      21.0   
90   Volkswagen  Corrado   Sporty  22.900000   23.3  23.700000      18.0   
91        Volvo      240  Compact  21.800000   22.7  23.500000      21.0   
92          NaN      850  Midsize  24.800000   26.7  28.500000      20.0   

    MPG.highway             AirBags DriveTrain  ... Passengers  Length  \
0          31.0                 NaN      Front  ...        5.0   177.0   
1          25.0  Driver & Passenger      Front  ...        5.0   195.0   
2          26.0         Driver only      Front  ...        5.0   180.0   
3          26.0  Driver & Passenger        NaN  ...        6.0   193.0   
4          30.0                 NaN       Rear  ...        4.0   186.0   
..          ...                 ...        ...  ...        ...     ...   
88         21.0                 NaN      Front  ...        7.0   187.0   
89         30.0                 NaN      Front  ...        5.0   180.0   
90         25.0                 NaN      Front  ...        4.0   159.0   
91         28.0         Driver only       Rear  ...        5.0   190.0   
92         28.0  Driver & Passenger      Front  ...        5.0   184.0   

    Wheelbase  Width  Turn.circle Rear.seat.room  Luggage.room  Weight  \
0       102.0   68.0         37.0           26.5           NaN  2705.0   
1       115.0   71.0         38.0           30.0          15.0  3560.0   
2       102.0   67.0         37.0           28.0          14.0  3375.0   
3       106.0    NaN         37.0           31.0          17.0  3405.0   
4       109.0   69.0         39.0           27.0          13.0  3640.0   
..        ...    ...          ...            ...           ...     ...   
88      115.0   72.0         38.0           34.0           NaN  3960.0   
89      103.0   67.0         35.0           31.5          14.0  2985.0   
90       97.0   66.0         36.0           26.0          15.0  2810.0   
91      104.0   67.0         37.0           29.5          14.0  2985.0   
92      105.0   69.0         38.0           30.0          15.0  3245.0   

     Origin                Make  
0   non-USA       Acura Integra  
1   non-USA        Acura Legend  
2   non-USA             Audi 90  
3   non-USA            Audi 100  
4   non-USA            BMW 535i  
..      ...                 ...  
88      NaN  Volkswagen Eurovan  
89  non-USA   Volkswagen Passat  
90  non-USA  Volkswagen Corrado  
91  non-USA           Volvo 240  
92  non-USA           Volvo 850  

[93 rows x 27 columns]

3. How to get the rows of a dataframe with row sum > 100?

```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
```

In [363]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

ans_df = df.where(df.sum(axis=1, numeric_only = True) > 100)
ans_df.dropna(how = 'all', inplace = True)
ans_df

0     1     2     3
1   36.0  21.0  37.0  29.0
4   34.0  28.0  35.0  21.0
5   19.0  22.0  35.0  32.0
6   25.0  29.0  29.0  18.0
12  38.0  29.0  28.0  31.0